apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: ipam
    app.kubernetes.io/part-of: ipam
    app.kubernetes.io/version: tbd
  name: ipam-controller-controller-role
rules:
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - ipam.nephio.org
  resources:
  - ipallocations
  - ipallocations/status
  - ipprefixes
  - ipprefixes/status
  - networkinstances
  - networkinstances/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
