//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANClaim) DeepCopyInto(out *VXLANClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANClaim.
func (in *VXLANClaim) DeepCopy() *VXLANClaim {
	if in == nil {
		return nil
	}
	out := new(VXLANClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VXLANClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANClaimCtx) DeepCopyInto(out *VXLANClaimCtx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANClaimCtx.
func (in *VXLANClaimCtx) DeepCopy() *VXLANClaimCtx {
	if in == nil {
		return nil
	}
	out := new(VXLANClaimCtx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANClaimList) DeepCopyInto(out *VXLANClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VXLANClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANClaimList.
func (in *VXLANClaimList) DeepCopy() *VXLANClaimList {
	if in == nil {
		return nil
	}
	out := new(VXLANClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VXLANClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANClaimSpec) DeepCopyInto(out *VXLANClaimSpec) {
	*out = *in
	out.VXLANIndex = in.VXLANIndex
	in.ClaimLabels.DeepCopyInto(&out.ClaimLabels)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANClaimSpec.
func (in *VXLANClaimSpec) DeepCopy() *VXLANClaimSpec {
	if in == nil {
		return nil
	}
	out := new(VXLANClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANClaimStatus) DeepCopyInto(out *VXLANClaimStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.VXLANID != nil {
		in, out := &in.VXLANID, &out.VXLANID
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANClaimStatus.
func (in *VXLANClaimStatus) DeepCopy() *VXLANClaimStatus {
	if in == nil {
		return nil
	}
	out := new(VXLANClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANIndex) DeepCopyInto(out *VXLANIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANIndex.
func (in *VXLANIndex) DeepCopy() *VXLANIndex {
	if in == nil {
		return nil
	}
	out := new(VXLANIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VXLANIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANIndexList) DeepCopyInto(out *VXLANIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VXLANIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANIndexList.
func (in *VXLANIndexList) DeepCopy() *VXLANIndexList {
	if in == nil {
		return nil
	}
	out := new(VXLANIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VXLANIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANIndexSpec) DeepCopyInto(out *VXLANIndexSpec) {
	*out = *in
	in.UserDefinedLabels.DeepCopyInto(&out.UserDefinedLabels)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANIndexSpec.
func (in *VXLANIndexSpec) DeepCopy() *VXLANIndexSpec {
	if in == nil {
		return nil
	}
	out := new(VXLANIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VXLANIndexStatus) DeepCopyInto(out *VXLANIndexStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VXLANIndexStatus.
func (in *VXLANIndexStatus) DeepCopy() *VXLANIndexStatus {
	if in == nil {
		return nil
	}
	out := new(VXLANIndexStatus)
	in.DeepCopyInto(out)
	return out
}
