//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLAN) DeepCopyInto(out *VLAN) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLAN.
func (in *VLAN) DeepCopy() *VLAN {
	if in == nil {
		return nil
	}
	out := new(VLAN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLAN) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANClaim) DeepCopyInto(out *VLANClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANClaim.
func (in *VLANClaim) DeepCopy() *VLANClaim {
	if in == nil {
		return nil
	}
	out := new(VLANClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLANClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANClaimCtx) DeepCopyInto(out *VLANClaimCtx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANClaimCtx.
func (in *VLANClaimCtx) DeepCopy() *VLANClaimCtx {
	if in == nil {
		return nil
	}
	out := new(VLANClaimCtx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANClaimList) DeepCopyInto(out *VLANClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VLANClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANClaimList.
func (in *VLANClaimList) DeepCopy() *VLANClaimList {
	if in == nil {
		return nil
	}
	out := new(VLANClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLANClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANClaimSpec) DeepCopyInto(out *VLANClaimSpec) {
	*out = *in
	out.VLANIndex = in.VLANIndex
	if in.VLANID != nil {
		in, out := &in.VLANID, &out.VLANID
		*out = new(uint16)
		**out = **in
	}
	if in.VLANRange != nil {
		in, out := &in.VLANRange, &out.VLANRange
		*out = new(string)
		**out = **in
	}
	in.ClaimLabels.DeepCopyInto(&out.ClaimLabels)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANClaimSpec.
func (in *VLANClaimSpec) DeepCopy() *VLANClaimSpec {
	if in == nil {
		return nil
	}
	out := new(VLANClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANClaimStatus) DeepCopyInto(out *VLANClaimStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.VLANID != nil {
		in, out := &in.VLANID, &out.VLANID
		*out = new(uint16)
		**out = **in
	}
	if in.VLANRange != nil {
		in, out := &in.VLANRange, &out.VLANRange
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANClaimStatus.
func (in *VLANClaimStatus) DeepCopy() *VLANClaimStatus {
	if in == nil {
		return nil
	}
	out := new(VLANClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANIndex) DeepCopyInto(out *VLANIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANIndex.
func (in *VLANIndex) DeepCopy() *VLANIndex {
	if in == nil {
		return nil
	}
	out := new(VLANIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLANIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANIndexList) DeepCopyInto(out *VLANIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VLANIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANIndexList.
func (in *VLANIndexList) DeepCopy() *VLANIndexList {
	if in == nil {
		return nil
	}
	out := new(VLANIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLANIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANIndexSpec) DeepCopyInto(out *VLANIndexSpec) {
	*out = *in
	in.UserDefinedLabels.DeepCopyInto(&out.UserDefinedLabels)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANIndexSpec.
func (in *VLANIndexSpec) DeepCopy() *VLANIndexSpec {
	if in == nil {
		return nil
	}
	out := new(VLANIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANIndexStatus) DeepCopyInto(out *VLANIndexStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANIndexStatus.
func (in *VLANIndexStatus) DeepCopy() *VLANIndexStatus {
	if in == nil {
		return nil
	}
	out := new(VLANIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANList) DeepCopyInto(out *VLANList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VLAN, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANList.
func (in *VLANList) DeepCopy() *VLANList {
	if in == nil {
		return nil
	}
	out := new(VLANList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLANList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANSpec) DeepCopyInto(out *VLANSpec) {
	*out = *in
	out.VLANIndex = in.VLANIndex
	if in.VLANID != nil {
		in, out := &in.VLANID, &out.VLANID
		*out = new(uint16)
		**out = **in
	}
	if in.VLANRange != nil {
		in, out := &in.VLANRange, &out.VLANRange
		*out = new(string)
		**out = **in
	}
	in.UserDefinedLabels.DeepCopyInto(&out.UserDefinedLabels)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANSpec.
func (in *VLANSpec) DeepCopy() *VLANSpec {
	if in == nil {
		return nil
	}
	out := new(VLANSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANStatus) DeepCopyInto(out *VLANStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.VLANID != nil {
		in, out := &in.VLANID, &out.VLANID
		*out = new(uint16)
		**out = **in
	}
	if in.VLANRange != nil {
		in, out := &in.VLANRange, &out.VLANRange
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANStatus.
func (in *VLANStatus) DeepCopy() *VLANStatus {
	if in == nil {
		return nil
	}
	out := new(VLANStatus)
	in.DeepCopyInto(out)
	return out
}
