apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
    app.kubernetes.io/version: tbd
  name: resource-backend-controller-controller-role
rules:
- apiGroups:
  - '*'
  resources:
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - inv.nephio.org
  resources:
  - endpoints
  - endpoints/status
  - links
  - links/status
  - nodes
  - nodes/status
  - targets
  - targets/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - ipam.resource.nephio.org
  resources:
  - ipclaims
  - ipclaims/status
  - ipprefixes
  - ipprefixes/status
  - networkinstances
  - networkinstances/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - topo.nephio.org
  resources:
  - rawtopologies
  - rawtopologies/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - vlan.resource.nephio.org
  resources:
  - vlanclaims
  - vlanclaims/status
  - vlanindices
  - vlanindices/status
  - vlans
  - vlans/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
