apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
    app.kubernetes.io/version: tbd
  name: resource-backend-controller-porch-role
rules:
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  - packagerevisions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources/status
  - packagerevisions/status
  - packagerevisions/approval
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ipam.alloc.nephio.org
  resources:
  - ipallocations
  - ipallocations/status
  - ipprefixes
  - ipprefixes/status
  - networkinstances
  - networkinstances/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - vlan.alloc.nephio.org
  resources:
  - vlanallocations
  - vlanallocations/status
  - vlandatabases
  - vlandatabases/status
  - vlans
  - vlans/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
