# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# this config maps contains an entrypoint script that ensures that we first call the
# topomac script before executing the main entrypoint
apiVersion: v1
kind: ConfigMap
metadata:
  name: srlinux.nokia.com-k8s-entrypoint
  annotations: {}
data:
  k8s-entrypoint.sh: |
    #!/bin/bash
    # this entrypoint ensures that we call topomac script before executing the main entrypoint

    sudo bash /tmp/topomac/topomac.sh
    echo "topomac.sh" script finished

    # copy potentially provided startup config files
    sudo cp -L /tmp/initial-config/* /etc/opt/srlinux/

    exec /entrypoint.sh "$@"
