apiVersion: ipam.nephio.org/v1alpha1
kind: IPAllocation
metadata:
  name: us-central1.edge2.net1.alloc1
spec:
  kind: network
  networkInstanceRef: 
    namespace: default
    name: vpc2
  selector:
    matchLabels:
      nephio.org/region: us-central1
      nephio.org/site: edge2
      nephio.org/network-name: net1