apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
  name: resource-backend-controller-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-backend-controller-controller-role
subjects:
- kind: ServiceAccount
  name: resource-backend-controller
  namespace: backend-system
