apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
  name: resource-backend-controller
  namespace: backend-system
