apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
    fn.kptgen.dev/grpc: resource-backend-controller
  name: resource-backend-controller-grpc-svc
  namespace: backend-system
spec:
  ports:
  - name: grpc
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    fn.kptgen.dev/grpc: resource-backend-controller
status:
  loadBalancer: {}